#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@nelink[-1]
	add ucitrack nelink
	set ucitrack.@nelink[-1].init=nelink
	commit ucitrack
EOF
chmod +x /etc/init.d/nelink
rm -rf /tmp/luci-indexcache /tmp/luci-modulecache
exit 0
