#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1
PROG=/usr/bin/netlink

start_instance() {
	local cfg="$1"

	local type
	config_get type "$cfg" TYPE

	case "$type" in
	nelink)
		local enabled
		config_get_bool enabled "$cfg" 'enabled' '0'
		[ "$enabled" = "1" ] || return 1
		pgrep -f $PROG | xargs kill -9 >/dev/null 2>&1
		[ -x "$PROG" ] || chmod +x $PROG
		local masquerade tunname mode ipaddr prefix mtu
		local supernode port second_supernode second_port
		local community key route
		config_get_bool showtopics "$cfg" 'showtopics' '0'
		config_get host "$cfg" 'host' 
		config_get port "$cfg" 'port'
		config_get ipaddr "$cfg" 'ipaddr'
		config_get clientid "$cfg" 'clientid'
		config_get tunname "$cfg" 'tunname' 
		config_get username "$cfg" 'username'
		config_get password "$cfg" 'password'
		config_get_bool route "$cfg" 'route' '0'

    	
		local address
		address="$ipaddr/$prefix"
		[ "$mode" != 'dhcp' ] || address='0.0.0.0'

		procd_open_instance "nelink_$cfg"
		CMD="--tun-name ${tunname}"
		[ -z "$clientid" ] || CMD="${CMD} -g ${clientid}"
		[ -z "$ipaddr" ] || CMD="${CMD} -l ${ipaddr}/24"
		[ -z "$host" ] || CMD="${CMD} -p ${host}"
		[ -z "$port" ] || CMD="${CMD} --api-addr ${port}"
		procd_set_param command /bin/sh -c  "${PROG}  ${CMD} >> /var/log/nelink.log 2>&1"
		procd_set_param stdout 1
		procd_set_param stderr 1
		procd_set_param respawn
		procd_close_instance
		check_log

               if [ -z "$tunname" ] ; then
                   nelink0="$nelink0"
                else
                   nelink0="$tunname"
                fi 
                if [ ! -z "$PROG_port" ] ; then
                   if [ ! -z "$(echo $PROG_port | grep ',' )" ] ; then
	              nelink_tcp_port="${PROG_port%%,*}"
	           else
                      nelink_tcp_port="$PROG_port"
                    fi
	            uci -q delete firewall.nelink
		    uci set firewall.nelink=rule
		    uci set firewall.nelink.name="nelink"
		    uci set firewall.nelink.target="ACCEPT"
		    uci set firewall.nelink.src="wan"
		    uci set firewall.nelink.proto="tcp"
		    uci set firewall.nelink.dest_port="$nelink_tcp_port"
		    uci set firewall.nelink.enabled="1"
	        fi
		#nelink_ip="$($PROG --info | awk -F 'Virtual ip:' {'print $2'} | tr -d ' \n')"
                if [ -z "$(uci -q get network.NELINK)" ];  then				
			uci set network.NELINK='interface'
			if [ -z "$ipaddr" ]; then
				uci set network.NELINK.proto='none'
			else
				uci set network.NELINK.proto='static'
				uci set network. NELINK.ipaddr=$ipaddr
				uci set network.NELINK.netmask='255.255.255.0'
			fi
                        uci set network.NELINK.device=$nelink0
                        uci set network.NELINK.ifname=$nelink0
		fi
                if [ -z "$(uci -q get firewall.nelinkzone)" ];  then
				uci set firewall.nelinkzone='zone'
				uci set firewall.nelinkzone.input='ACCEPT'
				uci set firewall.nelinkzone.output='ACCEPT'
				uci set firewall.nelinkzone.forward='ACCEPT'
				uci set firewall.nelinkzone.masq='1'
                                uci set firewall.nelinkzone.mtu_fix='1'
				uci set firewall.nelinkzone.name='NELINK'
				uci set firewall.nelinkzone.network='NELINK'
		fi
                uci set firewall.nelinkfwlan=forwarding
		uci set firewall.nelinkfwlan.dest='lan'
		uci set firewall.nelinkfwlan.src='NELINK'
                uci set firewall.nelinkfwwan=forwarding
		uci set firewall.nelinkfwwan.dest='wan'
		uci set firewall.nelinkfwwan.src='NELINK'
                uci set firewall.lanfwnelink=forwarding
		uci set firewall.lanfwnelink.dest='NELINK'
		uci set firewall.lanfwnelink.src='lan'
                uci set firewall.wanfwnelink=forwarding
		uci set firewall.wanfwnelink.dest='NELINK'
		uci set firewall.wanfwnelink.src='wan'
                [ -n "$(uci changes network)" ] && uci commit network && /etc/init.d/network reload >/dev/null 2>&1
		[ -n "$(uci changes firewall)" ] && uci commit firewall && /etc/init.d/firewall reload >/dev/null 2>&1
		[ "$forward" = "0" ] || sysctl -w net.ipv4.ip_forward=1 >/dev/null 2>&1
                [ ! -z "$checkip" ] && check
                echo `date +%s` > /tmp/nelink_time
	;;
	route)
		local enabled
		config_get_bool enabled "$cfg" 'enabled' '0'
		[ "$enabled" = "1" ] || return 1

		local ip mask gw
		config_get ip "$cfg" 'ip'
		config_get mask "$cfg" 'mask'
		config_get gw "$cfg" 'gw'
		route add -net "${ip}/${mask}" gw "${gw}"
	esac
}

start_service() {
	config_load 'nelink'
	config_foreach start_instance 'nelink'
	( sleep 2; config_foreach start_instance 'route'; ) &
}

stop_service() {
	pgrep -f nelink_checklog | xargs kill -9 >/dev/null 2>&1
	pgrep -f netlink | xargs kill -9 >/dev/null 2>&1
	echo "[INFO] [$(date '+%Y-%m-%d %H:%M:%S')]：停止运行" >/var/log/nelink.log
}

service_triggers() {
      procd_add_reload_trigger "nelink"
}
