#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-ntwon
PKG_VERSION:=v2.04
PKG_RELEASE:=1

LUCI_TITLE:=LuCI support for ntwon
LUCI_DEPENDS:=+kmod-tun
LUCI_PKGARCH:=all


include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
