#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2020 OpenWrt.org

START=99
USE_PROCD=1
size="$(df -k | awk '/\/overlay$/ {sub(/K$/, "", $4); print $4}')"

start_hxcli() {
                local cfg="$1"
		local enabled
		config_get_bool enabled "$cfg" 'enabled' '0'
		[ "$enabled" = "1" ] || return 1
                config_get clibin "$cfg" 'clibin'
                if [ -z "$clibin" ] ;then
                   clibin=/tmp/hx-cli
                fi
                echo "$(date '+%Y-%m-%d %H:%M:%S') hx-cli : 开始启动" >>/log/hx-cli.log
		echo "$(date '+%Y-%m-%d %H:%M:%S') hx-cli : 若启动失败，请打开 状态 - 系统日志 找到hxzn相关的字眼查看启动失败错误的原因" >>/tmp/hx-cli.log
                path=$(dirname "$clibin")
                if [ -f /tmp/hx-cli ] && [ "${path:0:4}" != "/tmp" ] ;then
                   chmod +x /tmp/hx-cli
                   echo "$(date '+%Y-%m-%d %H:%M:%S') hx-cli : 找到上传的程序/tmp/hx-cli，替换为$clibin " >>/log/hx-cli.log
                   upsize="$(du -k /tmp/hx-cli | cut -f1)"
                   result=$(expr $size - $upsize)
                   if [ $(($(/tmp/hx-cli -h | wc -l))) -gt 3 ] && [ "$result" -gt 500 ] ; then
                     mv -f /tmp/hx-cli "$clibin"
                     else
                     echo "$(date '+%Y-%m-%d %H:%M:%S') hx-cli : 无法替换，上传的程序不完整或自定义路径的可用空间不足，当前空间剩余${size}kb" >>/log/hx-cli.log
                   fi
                fi
                if [ ! -f "$clibin" ] && [ "$size" -lt 4000 ] ; then
                    echo "$(date '+%Y-%m-%d %H:%M:%S') hx-cli : 自定义程序路径的可用空间不足，当前可用空间剩余${size}kb,自动切换为内存/tmp/hx-cli" >>/log/hx-cli.log
                    sed -i "/clibin/c option clibin '/tmp/hx-cli' " /etc/config/hxzn 
                    clibin=/tmp/hx-cli
                fi
		if [ $(($($clibin -h | wc -l))) -lt 3 ] || [ ! -f "$clibin" ] ; then
		 echo "$(date '+%Y-%m-%d %H:%M:%S') hx-cli : 未找到程序 $clibin 开始在线下载，下载较慢耐心等候" >>/log/hx-cli.log
                 mkdir -p "$path"
case "${cpucore}" in 
	"mipsle")  curl -o "${clibin}" --connect-timeout 10 --retry 3 http://free1.fujufrp.cf:19213/vnt-cli_mipsle
	;;
	"mips")  curl -o "${clibin}" --connect-timeout 10 --retry 3 http://free1.fujufrp.cf:19213/vnt-cli_mips
	;;
	"x86_64")  curl -o "${clibin}" --connect-timeout 10 --retry 3 http://free1.fujufrp.cf:19213/vnt-cli_x86_64
	;;
	"i386")  curl -o "${clibin}" --connect-timeout 10 --retry 3 http://free1.fujufrp.cf:19213/vnt-cli_i386
	;;
	"arm")  curl -o "${clibin}" --connect-timeout 10 --retry 3 http://free1.fujufrp.cf:19213/vnt-cli_arm
	;;
	"armv7")  curl -o "${clibin}" --connect-timeout 10 --retry 3 http://free1.fujufrp.cf:19213/vnt-cli_armv7
	;;
	"aarch64")  curl -o "${clibin}" --connect-timeout 10 --retry 3 http://free1.fujufrp.cf:19213/vnt-cli_aarch64
	;;
esac
 chmod +x "$clibin"
 if [ $(($($clibin -h | wc -l))) -gt 3 ]; then
    echo "$(date '+%Y-%m-%d %H:%M:%S') hx-cli : ${clibin} 下载成功" >>/log/hx-cli.log
 else
   uci -q set hxzn.@hx-cli[0].enabled=0
   uci commit
   echo "$(date '+%Y-%m-%d %H:%M:%S') hx-cli : $clibin 下载失败，请手动下载上传程序,程序退出" >>/log/hx-cli.log
   return 1
 fi
                fi
                chmod +x "$clibin"
                ver="$($clibin -h | grep version | awk -F ':' {'print $2'})"
                [ ! -z "$ver" ] && echo "$(date '+%Y-%m-%d %H:%M:%S') hxzn : ${clibin}当前版本号-${ver} " >>/log/hx-cli.log
                pgrep -f hxzn_check | xargs kill -9 >/dev/null 2>&1
                ps | grep 'hx-cli' | grep -v grep | awk '{print $1}' | xargs kill >/dev/null 2>&1
                ps | grep 'hx-cli' | grep -v grep | awk '{print $1}' | xargs kill -9 >/dev/null 2>&1
		local token mode ipaddr mtu desvice_id localadd log
		local peeradd desvice_name hxznshost stunhost checkip
		local punch client_port par key forward serverw 
		local finger relay first_latency multicast tunmode tcp passmode
		config_get token "$cfg" 'token'
                config_get hxzndns "$cfg" 'hxzndns'
                config_get desvice_id "$cfg" 'desvice_id'
                config_get desvice_name "$cfg" 'desvice_name'
                config_get hxznshost "$cfg" 'hxznshost'
                config_get local_dev "$cfg" 'local_dev'
                config_get stunhost "$cfg" 'stunhost'
                config_get client_port "$cfg" 'client_port'
                config_get punch "$cfg" 'punch' 'all'
                config_get passmode "$cfg" 'passmode'
                config_get peeradd "$cfg" 'peeradd'
                config_get localadd "$cfg" 'localadd'
		config_get mode "$cfg" 'mode'
		config_get ipaddr "$cfg" 'ipaddr'
		config_get mtu "$cfg" 'mtu'
		config_get tunname "$cfg" 'tunname'
		config_get key "$cfg" 'key'
		config_get relay "$cfg" 'relay'
		config_get_bool serverw "$cfg" 'serverw' '0'
		config_get_bool forward "$cfg" 'forward' '0'
		config_get_bool finger "$cfg" 'finger' '0'
		config_get_bool first_latency "$cfg" 'first_latency' '0'
                config_get_bool log "$cfg" 'log' '0'
                config_get_bool disable_stats "$cfg" 'disable_stats' '0'
                config_get_bool allow_wg "$cfg" 'allow_wg' '0'
                config_get checkip "$cfg" 'checkip'
                config_get comp "$cfg" 'comp'
                config_get mapping "$cfg" 'mapping'
                config_get checkip "$cfg" 'checkip'

               if [ "$log" = "1" ] ;then
                 if [ ! -f /tmp/log4rs.yaml ] ; then
                  cat > /tmp/log4rs.yaml<<EOF
refresh_rate: 30 seconds
appenders:
  rolling_file:
    kind: rolling_file
    path: /tmp/hx-cli.log
    append: true
    encoder:
      pattern: "{d} [{f}:{L}] {h({l})} {M}:{m}{n}"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 1 mb
      roller:
        kind: fixed_window
        pattern: log/hx-cli.{}.log
        base: 1
        count: 2

root:
  level: info
  appenders:
    - rolling_file
EOF
           fi
        [ ! -L /log4rs.yaml ] && rm -rf /log4rs.yaml && ln -sf /tmp/log4rs.yaml /log4rs.yaml
        [ ! -L /tmp/hx-cli.0.log ] && ln -sf /tmp/hx-cli.log /tmp/hx-cli.0.log
        [ ! -L /tmp/hx-cli.1.log ] && ln -sf /tmp/hx-cli.log /tmp/hx-cli.1.log
	[ ! -L /tmp/hx-cli.2.log ] && ln -sf /tmp/hx-cli.log /tmp/hx-cli.2.log
      else
      rm -rf /tmp/log4rs.yaml
          fi
		procd_open_instance "hx-cli"
		procd_set_param command "$clibin"
		procd_append_param command -k "$token"
		[ -z "$ipaddr" ] || procd_append_param command --ip "$ipaddr"
		[ -z "$mtu" ] || procd_append_param command -u "$mtu"
		[ -z "$desvice_id" ] || procd_append_param command -d "$desvice_id"
		[ -z "$desvice_name" ] || procd_append_param command -n "$desvice_name"
		[ -z "$hxznshost" ] || procd_append_param command -s "$hxznshost"
		[ -z "$client_port" ] || procd_append_param command --port "$client_port"
		if [ ! -z "$peeradd" ] ; then
                  if [[ "$(grep "list peeradd" /etc/config/hxzn | awk '{print $3}' | wc -l ) " -eq 1 ]]; then
                    procd_append_param command -i "$peeradd"
                  else
                    for peeraddr in $(cat /etc/config/hxzn | grep 'list peeradd'  | awk '{print $3}'| sed "s/'/\n/g" | tr -d " ' "); do
                    procd_append_param command -i "$peeraddr"
                   done
                   fi
                fi

                if [ ! -z "$localadd" ] ; then
                  if [[ "$(grep "list localadd" /etc/config/hxzn | awk '{print $3}' | wc -l ) " -eq 1 ]]; then
                     procd_append_param command -o "$localadd"
                 else
                   for localaddr in $(cat /etc/config/hxzn | grep 'list localadd'  | awk '{print $3}'| sed "s/'/\n/g" | tr -d " ' "); do
                   procd_append_param command -o "$localaddr"
                   done
                   fi

                fi
                if [ ! -z "$hxzndns" ] ; then
                  if [[ "$(grep "list hxzndns" /etc/config/hxzn | awk '{print $3}' | wc -l ) " -eq 1 ]]; then
                    procd_append_param command --dns "$hxzndns"
                  else
                    for hxzndnss in $(cat /etc/config/hxzn | grep 'list hxzndns'  | awk -F 'list hxzndns' '{print $2}' | sed "s/'/\n/g" | tr -d " ' "); do
                    procd_append_param command --dns "$hxzndnss"
                   done
                   fi
                fi

                if [ ! -z "$stunhost" ] ; then
                  if [[ "$(grep "list stunhost" /etc/config/hxzn | awk '{print $3}' | wc -l ) " -eq 1 ]]; then
                    procd_append_param command -e "$stunhost"
                  else
                    for stunhosts in $(cat /etc/config/hxzn | grep 'list stunhost'  | awk '{print $3}'| sed "s/'/\n/g" | tr -d " ' "); do
                    procd_append_param command -e "$stunhosts"
                   done
                   fi
                fi

                if [ ! -z "$mapping" ] ; then
                  if [[ "$(grep "list mapping" /etc/config/hxzn | awk '{print $3}' | wc -l ) " -eq 1 ]]; then
                    procd_append_param command --mapping "$mapping"
                  else
                    for mappings in $(cat /etc/config/hxzn | grep 'list mapping'  | awk -F 'list mapping' '{print $2}' | sed "s/'/\n/g" | tr -d " ' "); do
                    procd_append_param command --mapping "$mappings"
                   done
                   fi
                fi
		[ -z "$tunname" ] || procd_append_param command --nic "$tunname"
		[ -z "$local_dev" ] || procd_append_param command --local-dev "$local_dev"
		[ -z "$par" ] || procd_append_param command --par "$par"
		[ "$punch" = "ipv4/ipv6" ] || procd_append_param command --punch "$punch"
		[ "$passmode" != "off" ] && [ -n "$key" ] && procd_append_param command --model "$passmode"
		[ "$passmode" != "off" ] && [ -n "$key" ] && procd_append_param command -w "$key"
                [ "$allow_wg" = "0" ] || procd_append_param command --allow-wg
		[ "$forward" = "0" ] || procd_append_param command --no-proxy
		[ "$finger" = "0" ] || procd_append_param command --finger
		[ "$serverw" = "0" ] || procd_append_param command -W
                [ "$disable_stats" = "1" ] || procd_append_param command --disable-stats
		[ "$first_latency" = "0" ] || procd_append_param command --first-latency
                [ "$relay" = "转发" ] && procd_append_param command --use-channel relay
                [ "$relay" = "P2P" ] && procd_append_param command --use-channel p2p
                [ "$comp" != "OFF" ] && procd_append_param command --compressor "$comp"

		procd_set_param limits core="unlimited"
		procd_set_param limits nofile="1000000 1000000"
		procd_set_param stdout 1
		procd_set_param stderr 1
		procd_set_param respawn
		procd_close_instance

                if [ -z "$tunname" ] ; then
                   vnt_tun="vnt-tun"
                else
                   vnt_tun="$tunname"
                fi 
                if [ ! -z "$client_port" ] ; then
                   if [ ! -z "$(echo $client_port | grep ',' )" ] ; then
	              hxzn_tcp_port="${client_port%%,*}"
	           else
                      hxzn_tcp_port="$client_port"
                    fi
	            uci -q delete firewall.hxzncli
		    uci set firewall.hxzncli=rule
		    uci set firewall.hxzncli.name="hxzncli"
		    uci set firewall.hxzncli.target="ACCEPT"
		    uci set firewall.hxzncli.src="wan"
		    uci set firewall.hxznncli.proto="tcp"
		    uci set firewall.hxzncli.dest_port="$hxzn_tcp_port"
		    uci set firewall.hxzncli.enabled="1"
	        fi
		#hxzn_ip="$($clibin --info | awk -F 'Virtual ip:' {'print $2'} | tr -d ' \n')"
                if [ -z "$(uci -q get network.HXZN)" ];  then				
			uci set network.HXZN='interface'
			if [ -z "$ipaddr" ]; then
				uci set network.HXZN.proto='none'
			else
				uci set network.HXZN.proto='static'
				uci set network.HXZN.ipaddr=$ipaddr
				uci set network.HXZN.netmask='255.255.255.0'
			fi
                        uci set network.HXZN.device=$vnt_tun
                        uci set network.HXZN.ifname=$vnt_tun
		fi
                if [ -z "$(uci -q get firewall.hxznzone)" ];  then
				uci set firewall.hxznzone='zone'
				uci set firewall.hxznzone.input='ACCEPT'
				uci set firewall.hxznzone.output='ACCEPT'
				uci set firewall.hxznzone.forward='ACCEPT'
				uci set firewall.hxznzone.masq='1'
                                uci set firewall.hxznzone.mtu_fix='1'
				uci set firewall.hxznzone.name='HXZN'
				uci set firewall.hxznzone.network='HXZN'
		fi
                uci set firewall.hxznfwlan=forwarding
		uci set firewall.hxznfwlan.dest='lan'
		uci set firewall.hxznfwlan.src='HXZN'
                uci set firewall.hxznfwwan=forwarding
		uci set firewall.hxznfwwan.dest='wan'
		uci set firewall.hxznfwwan.src='HXZN'
                uci set firewall.lanfwhxzn=forwarding
		uci set firewall.lanfwhxzn.dest='HXZN'
		uci set firewall.lanfwhxzn.src='lan'
                uci set firewall.wanfwhxzn=forwarding
		uci set firewall.wanfwhxzn.dest='HXZN'
		uci set firewall.wanfwhxzn.src='wan'
                [ -n "$(uci changes network)" ] && uci commit network && /etc/init.d/network reload >/dev/null 2>&1
		[ -n "$(uci changes firewall)" ] && uci commit firewall && /etc/init.d/firewall reload >/dev/null 2>&1
		[ "$forward" = "0" ] || sysctl -w net.ipv4.ip_forward=1 >/dev/null 2>&1
                [ ! -z "$checkip" ] && check
                echo `date +%s` > /tmp/hxzn_time
                
}

check () {
if [ ! -z "$checkip" ] ; then
  echo ' ' >/tmp/hxzn_check
  cat > /tmp/hxzn_check<<'EOF'
#!/bin/sh
time="$(($(uci -q get hxzn.@hx-cli[0].checktime) * 60))"
  if [ -z "$time" ] ;then
     time=120
     uci -q set hxzn.@hx-cli[0].checktime=2
     uci commit
  fi 
while true; do
  if [ "$(uci -q get hxzn.@hx-cli[0].enabled)" = "1" ] ; then
    ping -c 3 223.5.5.5 -w 5 >/dev/null 2>&1
    if [ "$?" == "0" ]; then
        if [ ! -z "$(uci -q get hxzn.@hx-cli[0].checkip)" ] ; then
           online=""
           for ip in $(uci -q get hxzn.@hx-cli[0].checkip); do
           ms=`echo $(ping -4 $ip  -c 2 -w 4 -q) | awk -F '/' '{print $4}'`
           [ ! -z "$ms" ] && echo "$(date '+%Y-%m-%d %H:%M:%S') hx-cli : 通断检测：${ip} 延迟：${ms}ms " >>/log/hx-cli.log && online=1
           [ -z "$ms" ] && echo "$(date '+%Y-%m-%d %H:%M:%S') hx-cli : 通断检测：${ip} 网络中断 " >>/log/hx-cli.log
           done     
           [ "$online" != "1" ] && echo "$(date '+%Y-%m-%d %H:%M:%S') hx-cli : 通断检测：$(uci -q get hxzn.@hx-cli[0].checkip) 所有指定IP皆无法ping通,重新启动程序！ " >>/log/hx-cli.log && /etc/init.d/hxzn restart
        fi
     else
        echo "$(date '+%Y-%m-%d %H:%M:%S') hx-cli : 通断检测：检测到互联网未能成功访问，跳过检测 " >>/log/hx-cli.log
    fi
 else
 echo "$(date '+%Y-%m-%d %H:%M:%S') hxzn : 通断检测：程序已关闭，退出检测 " >>/log/hx-cli.log
 /etc/init.d/hxzn restart
 break
 fi
sleep $((time))
[ "$(du -k /log/hx-cli.log | cut -f1)" = "1000" ] && echo " " >/log/hx-cli.log
done
EOF
  chmod +x /tmp/hxzn_check
  procd_open_instance
  procd_set_param respawn
  procd_set_param command /tmp/hxzn_check
  procd_close_instance
fi
}

start_hxzns() {
                local cfg="$1"
		local enabled
		config_get_bool enabled "$cfg" 'enabled' '0'
		[ "$enabled" = "1" ] || return 1
		echo "$(date '+%Y-%m-%d %H:%M:%S') hxzns : hxzns_${cpucore}开始启动" >>/tmp/hxzns.log
		echo "$(date '+%Y-%m-%d %H:%M:%S') hxzns : 若启动失败，请打开 状态 - 系统日志 找到hxzn相关的字眼查看启动失败错误的原因" >>/tmp/hxzns.log
                config_get hxznsbin "$cfg" 'hxznsbin'
                if [ -z "$vsbin" ] ;then
                   hxznsbin=/tmp/hxzns
                fi
                if [ -f /tmp/hxzns ] && [ "${path:0:4}" != "/tmp" ] ;then
                   chmod +x /tmp/hxzns
                   echo "$(date '+%Y-%m-%d %H:%M:%S') hxzns : 找到上传的程序/tmp/vnts，替换为$hxznsbin " >>/tmp/hxzns.log
                   upsize="$(du -k /tmp/hxzns | cut -f1)"
                   result=$(expr $size - $upsize)
                   if [ "$(($(/tmp/hxzns -h 2>&1 | wc -l)))" -gt 3 ] && [ "$result" -gt 500 ] ; then
                     mv -f /tmp/hxzns "$hxznsbin"
                     else
		     [ -z "$size" ] && [ "$(($(/tmp/hxzns -h 2>&1 | wc -l)))" -gt 3 ] && mv -f /tmp/hxzns "$hxznsbin"
                     echo "$(date '+%Y-%m-%d %H:%M:%S') hxzns : 无法替换，上传的程序不完整或自定义路径的可用空间不足，当前空间剩余${size}kb" >>/tmp/hxzns.log
                   fi
                fi
                if [ ! -f "$hxznsbin" ] && [ "$size" -lt 10240 ] && [ ! -z "$size" ] ; then
                    echo "$(date '+%Y-%m-%d %H:%M:%S') hxzns : 自定义程序路径的可用空间不足，当前可用空间剩余${size}kb,自动切换为内存/tmp/hxzns" >>/tmp/hxzns.log
                    uci -q set hxzn.@hxzns[0].hxznsbin=/tmp/hxzns
                    uci commit
                    hxznsbin=/tmp/hxzns
                fi
                path=$(dirname "$hxznsbin")
                key_path="${path}/key"
                log_path="${path}/log"
		if [ "$($hxznsbin -h 2>&1 | wc -l)" -lt 3 ] || [ ! -f "$hxznsbin" ] ; then
		echo "$(date '+%Y-%m-%d %H:%M:%S') hxzns : ${hxznsbin} 不存在，开始在线下载，下载较慢耐心等候..." >>/tmp/hxzns.log
                mkdir -p "$path"
		if [ -z "$curltest" ] || [ ! -s "`which curl`" ] ; then
       			tag="$( wget -T 5 -t 3 --user-agent "$user_agent" --max-redirect=0 --output-document=-  https://api.github.com/repos/vnt-dev/vnts/releases/latest  2>&1 | grep 'tag_name' | cut -d\" -f4 )"
       			[ -z "$tag" ] && tag="$( wget --no-check-certificate -T 5 -t 3 --user-agent "$user_agent" --quiet --output-document=-  https://api.github.com/repos/vnt-dev/vnts/releases/latest  2>&1 | grep 'tag_name' | cut -d\" -f4 )"
       			[ -z "$tag" ] && tag="$( wget --no-check-certificate -T 5 -t 3 --user-agent "$user_agent" --quiet --output-document=-  https://dl.cnqq.cloudns.ch/https://api.github.com/repos/vnt-dev/vnts/releases/latest  2>&1 | grep 'tag_name' | cut -d\" -f4 )"
   		else
       			tag="$( curl --connect-timeout 3 --user-agent "$user_agent"  https://api.github.com/repos/vnt-dev/vnts/releases/latest  2>&1 | grep 'tag_name' | cut -d\" -f4 )"
       			[ -z "$tag" ] && tag="$( curl -k --connect-timeout 3 --user-agent "$user_agent" -s  https://api.github.com/repos/vnt-dev/vnts/releases/latest  2>&1 | grep 'tag_name' | cut -d\" -f4 )"
       			[ -z "$tag" ] && tag="$( curl -Lk --connect-timeout 5 --user-agent "$user_agent" -s  https://dl.cnqq.cloudns.ch/https://api.github.com/repos/vnt-dev/vnts/releases/latest  2>&1 | grep 'tag_name' | cut -d\" -f4 )"
   		fi
                [ -z "$tag" ] && tag=v1.2.12
		case "${cpucore}" in 
	           "mipsle")  hxznsurl="https://github.com/vnt-dev/vnts/releases/download/${tag}/vnts-mipsel-unknown-linux-musl-${tag}.tar.gz"
		   ;;
	           "mips")  hxznsurl="https://github.com/vnt-dev/vnts/releases/download/${tag}/vnts-mips-unknown-linux-musl-${tag}.tar.gz"
	           ;;
	           "x86_64")  vntsurl="https://github.com/vnt-dev/vnts/releases/download/${tag}/vnts-x86_64-unknown-linux-musl-${tag}.tar.gz"
	           ;;
	           "i386")  echo "$(date '+%Y-%m-%d %H:%M:%S') hxzn : 不支持的架构,程序退出" >>/tmp/hxzns.log
                     return 1
	           ;;
	           "arm")  hxznsurl="https://github.com/vnt-dev/vnts/releases/download/${tag}/vnts-arm-unknown-linux-musleabi-${tag}.tar.gz"
	           ;;
	           "armv7")  hxznsurl="https://github.com/vnt-dev/vnts/releases/download/${tag}/vnts-armv7-unknown-linux-musleabi-${tag}.tar.gz"
	           ;;
	           "aarch64")  hxznsurl="https://github.com/vnt-dev/vnts/releases/download/${tag}/vnts-aarch64-unknown-linux-musl-${tag}.tar.gz"
	           ;;
                esac
		 for proxy in $proxys ; do
			curl -Lko /tmp/hxzns.tar.gz "${proxy}${hxznsurl}" || wget --no-check-certificate -O /tmp/hxzns.tar.gz "${proxy}${hxznsurl}"
		     if [ "$?" = 0 ] ; then
                   	tar zxf /tmp/hxzns.tar.gz -C /tmp/
                   	chmod +x /tmp/hxzns
                   	rm -rf /tmp/hxzns.tar.gz
                  	if [ "$(($(/tmp/hxzns -h 2>&1 | wc -l)))" -gt 3 ]; then
                    		echo "$(date '+%Y-%m-%d %H:%M:%S') hxzns : /tmp/hxzns 下载成功" >>/tmp/hxzns.log
                    		mv -f /tmp/hxzns "$hxznsbin"
				break
                 	else
                     		uci -q set hxzn.@hxzns[0].enabled=0
                     		uci commit hxzn
                     		echo "$(date '+%Y-%m-%d %H:%M:%S') hxzns : $hxznsbin 下载失败，请手动下载上传程序,程序退出" >>/tmp/hxzns.log
                     		return 1
                  	fi
		    else
			echo "$(date '+%Y-%m-%d %H:%M:%S') hxzns : $hxznsbin 下载失败，请手动下载上传程序,程序退出" >>/tmp/hxzns.log
		    fi
		 done
                fi
               chmod +x "$hxznsbin"
                ps | grep 'hxzns' | grep -v grep | awk '{print $1}' | xargs kill >/dev/null 2>&1
                ps | grep 'hxzns' | grep -v grep | awk '{print $1}' | xargs kill -9 >/dev/null 2>&1
		local server_port white_Token subnet servern_netmask logs sfinger web_port webuser webpass web web_wan
		config_get server_port "$cfg" 'server_port'
		config_get white_Token "$cfg" 'white_Token'
		config_get subnet "$cfg" 'subnet'
		config_get servern_netmask "$cfg" 'servern_netmask'
		config_get web_port "$cfg" 'web_port' 
		config_get webuser "$cfg" 'webuser'
		config_get webpass "$cfg" 'webpass'
		config_get_bool web "$cfg" 'web' '0'
                config_get_bool web_wan "$web_wan" 'web_wan' '0'
                config_get_bool logs "$cfg" 'logs' '0'
                config_get_bool sfinger "$cfg" 'sfinger' '0'

		procd_open_instance "hxzns"
		procd_set_param command "$hxznsbin"
		procd_append_param command --port "$server_port"

		if [ ! -z "$white_Token" ] ; then
                   if [[ "$(grep "list white_Token" /etc/config/hxzn | awk '{print $3}' | wc -l ) " -eq 1 ]]; then
                     procd_append_param command --white-token "$white_Token"
                   else
                   for white_Tokens in $(cat /etc/config/hxzn | grep 'list white_Token'  | awk -F 'list white_Token' '{print $2}' | sed "s/'/\n/g" | tr -d " ' "); do
                   procd_append_param command --white-token "$white_Tokens"
                   done
                   fi
                fi
		[ -z "$subnet" ] || procd_append_param command --gateway "$subnet"
		[ -z "$servern_netmask" ] || procd_append_param command --netmask "$servern_netmask"
                [ "$sfinger" = "0" ] || procd_append_param command --finger
                [ "$logs" = "1" ] || procd_append_param command --log-path /dev/null
                
                  if [ ! -f "${log_path}/log4rs.yaml" ] ; then
mkdir -p ${log_path}
cat > "${log_path}/log4rs.yaml"<<EOF
refresh_rate: 30 seconds
appenders:
  rolling_file:
    kind: rolling_file
    path: /tmp/hxzns.log
    append: true
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S hxzns:)} [{f}:{L}] {h({l})} {M}:{m}{n}"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 1 mb
      roller:
        kind: fixed_window
        pattern: /tmp/hxzns.{}.log
        base: 1
        count: 2

root:
  level: info
  appenders:
    - rolling_file
EOF
                   fi
                if [ "$web" = "1" ] && [ "$cpucore" != "mips" ] ; then
                  [ -z "$web_port" ] || procd_append_param command --web-port "$web_port"
		  [ -z "$webuser" ] || procd_append_param command --username "$webuser"
		  [ -z "$webpass" ] || procd_append_param command --password "$webpass"
		  [ -z "$web_port" ] && web_port=29870
		 else
                  [ "$cpucore" = "mips" ] && echo "$(date '+%Y-%m-%d %H:%M:%S') hxzns : mips架构不支持web界面" >>/tmp/hx-cli.log
                  [ "$cpucore" != "mips" ] && procd_append_param command --web-port 0
		fi

		procd_set_param limits core="unlimited"
		procd_set_param limits nofile="1000000 1000000"
		procd_set_param stdout 1
		procd_set_param stderr 1
		procd_set_param respawn
		procd_close_instance
 
                uci -q delete firewall.vnts
		uci set firewall.hxzns=rule
		uci set firewall.hxzns.name="hxzns"
		uci set firewall.hxzns.target="ACCEPT"
		uci set firewall.hxzns.src="wan"
		uci set firewall.hxzns.proto="tcp udp icmp igmp"
		uci set firewall.hxzns.dest_port="$server_port"
		uci set firewall.hxzns.enabled="1"
                if [ "$web" = "1" ] && [ "$web_wan" = "1" ] ; then
                   uci -q delete firewall.hxznsweb
		   uci set firewall.hxznsweb=rule
		   uci set firewall.hxznsweb.name="hxzns_web"
		   uci set firewall.hxznsweb.target="ACCEPT"
		   uci set firewall.hxznsweb.src="wan"
		   uci set firewall.hxznsweb.proto="tcp"
		   uci set firewall.hxznsweb.dest_port="$web_port"
		   uci set firewall.hxznsweb.enabled="1"
		fi
              [ -n "$(uci changes firewall)" ] && uci commit firewall && /etc/init.d/firewall reload >/dev/null 2>&1
	        [ "$(uci -q get hxzn.@hxzns[0].logs)" = "0" ] && rm -rf /tmp/hxzns*.log 
	      if [ "$logs" = "1" ] ;then
	       sed -i 's|limit: 10 mb|limit: 1 mb|g' ${log_path}/log4rs.yaml
	       sed -i 's|count: 5|count: 2|g' ${log_path}/log4rs.yaml
	       logyaml=$(cat ${log_path}/log4rs.yaml |grep path: | awk -F'path: ' '{print $2}')
               logyaml2=$(cat ${log_path}/log4rs.yaml | grep pattern: | awk -F'pattern: ' '{print $2}')
               if [ "$logyaml" != "/tmp/hxzns.log" ] ; then
                  sed -i "s|${logyaml}|/tmp/hxzns.log|g" ${log_path}/log4rs.yaml
                  sed -i "s|${logyaml2}|/tmp/hxzns.{}.log|g" ${log_path}/log4rs.yaml
               fi
               [ ! -L /tmp/hxzns.0.log ] && ln -sf /tmp/hxzns.log /tmp/hxzns.0.log
               [ ! -L /tmp/hxzns.1.log ] && ln -sf /tmp/hxzns.log /tmp/hxzns.1.log
		[ ! -L /tmp/hxzns.2.log ] && ln -sf /tmp/hxzns.log /tmp/vs.2.log
	      fi
              mkdir -p /tmp/hxzns_key
              [ ! -L /tmp/hxzns_key/public_key.pem ] && ln -sf ${key_path}/public_key.pem /tmp/hxzns_key/public_key.pem
              [ ! -L /tmp/hxzns_key/private_key.pem ] && ln -sf ${key_path}/private_key.pem /tmp/hxzns_key/private_key.pem
              echo `date +%s` > /tmp/hxzns_time
}

stop_cli() {
                local cfg="$1"
                pgrep -f hxzn_check | xargs kill -9 >/dev/null 2>&1
                ps | grep 'hx-cli' | grep -v grep | awk '{print $1}' | xargs kill >/dev/null 2>&1
                ps | grep 'hx-cli' | grep -v grep | awk '{print $1}' | xargs kill -9 >/dev/null 2>&1
                uci -q delete network.HXZN
                uci -q delete firewall.hxznzone
	        uci -q delete firewall.hxznfwlan
	        uci -q delete firewall.hxznfwwan
	        uci -q delete firewall.lanfwhxzn
	        uci -q delete firewall.wanfwhxzn
                uci -q delete firewall.hxzncli
                [ -n "$(uci changes network)" ] && uci commit network && /etc/init.d/network reload >/dev/null 2>&1
	        [ -n "$(uci changes firewall)" ] && uci commit firewall && /etc/init.d/firewall reload >/dev/null 2>&1
                rm -rf /tmp/hx-cli_info /tmp/hx-cli_all /tmp/hx-cli_list /tmp/hx-cli_route
                rm -rf /tmp/hx-cli.log /tmp/hx-cli*.log
                rm -rf /tmp/hxznnew.tag /tmp/hxzn.tag
                echo "$(date '+%Y-%m-%d %H:%M:%S') hx-cli : 停止运行" >>/tmp/hx-cli.log
}
stop_hxzns() {
	        local cfg="$1"
		local server_port
		config_get server_port "$cfg" 'server_port'
                ps | grep 'hxzns' | grep -v grep | awk '{print $1}' | xargs kill >/dev/null 2>&1
                ps | grep 'hxzns' | grep -v grep | awk '{print $1}' | xargs kill -9 >/dev/null 2>&1
		iptables -D INPUT -p udp --dport "$server_port" -j ACCEPT -m comment --comment 'hxzn hxzns' 2>"/dev/null"
                iptables -D INPUT -p tcp --dport "$server_port" -j ACCEPT -m comment --comment 'hxzn hxzns' 2>"/dev/null"
                rm -rf /log/hxzns*.log
                echo "$(date '+%Y-%m-%d %H:%M:%S') hxzns : 停止运行" >>/log/hxzns.log
}

start_service() {
	config_load 'hxzn'
	cputype=$(uname -ms | tr ' ' '_' | tr '[A-Z]' '[a-z]')
        [ -n "$(echo $cputype | grep -E "linux.*armv.*")" ] && cpucore="arm"
        [ -n "$(echo $cputype | grep -E "linux.*armv7.*")" ] && [ -n "$(cat /proc/cpuinfo | grep vfp)" ] && cpucore="armv7"
        [ -n "$(echo $cputype | grep -E "linux.*aarch64.*|linux.*armv8.*")" ] && cpucore="aarch64"
        [ -n "$(echo $cputype | grep -E "linux.*86.*")" ] && cpucore="i386"
        [ -n "$(echo $cputype | grep -E "linux.*86_64.*")" ] && cpucore="x86_64"
        if [ -n "$(echo $cputype | grep -E "linux.*mips.*")" ] ; then
           mipstype=$(echo -n I | hexdump -o 2>/dev/null | awk '{ print substr($2,6,1); exit}') 
           [ "$mipstype" = "0" ] && cpucore="mips" || cpucore="mipsle"
        fi
        proxys="https://github.moeyy.xyz/
	https://gh.llkk.cc/
	https://mirror.ghproxy.com/
	https://ghproxy.net/
	"
        #[ -z "`opkg list-installed | grep curl`" ] && echo "$(date '+%Y-%m-%d %H:%M:%S') hxzn : 未安装curl，请确定安装好curl " >>/tmp/hx-cli.log 
        #[ -z "`opkg list-installed | grep luci-lib-fs`" ] && echo "$(date '+%Y-%m-%d %H:%M:%S') hxzn : 未安装luci-lib-fs，请确定安装好luci-lib-fs " >>/tmp/hx-cli.log 
	config_foreach start_hxcli 'hx-cli'
	config_foreach start_hxzns 'hxzns'
}

stop_service() {
        [ "$(uci -q get hxzn.@hxzns[0].enabled)" = "0" ] && stop_hxzns 'hxzns'
        [ "$(uci -q get hxzn.@hx-cli[0].enabled)" = "0" ] && stop_cli
}

reload_service() {
	stop
	start
}

service_triggers() {
	procd_add_reload_trigger "hxzn"
        procd_add_interface_trigger "interface.*.up" wan /etc/init.d/hxzn reload
}
